config/routes.rb
Rails.application.routes.draw do
  resources :siswas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/siswa.rb
class Siswa < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/siswas_controller.rb
class SiswasController < ApplicationController
  before_action :set_siswa, only: [:show, :edit, :update, :destroy]

  # GET /siswas
  # GET /siswas.json
  def index
    @siswas = Siswa.all
  end

  # GET /siswas/1
  # GET /siswas/1.json
  def show
  end

  # GET /siswas/new
  def new
    @siswa = Siswa.new
  end

  # GET /siswas/1/edit
  def edit
  end

  # POST /siswas
  # POST /siswas.json
  def create
    @siswa = Siswa.new(siswa_params)

    respond_to do |format|
      if @siswa.save
        format.html { redirect_to @siswa, notice: 'Siswa was successfully created.' }
        format.json { render :show, status: :created, location: @siswa }
      else
        format.html { render :new }
        format.json { render json: @siswa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /siswas/1
  # PATCH/PUT /siswas/1.json
  def update
    respond_to do |format|
      if @siswa.update(siswa_params)
        format.html { redirect_to @siswa, notice: 'Siswa was successfully updated.' }
        format.json { render :show, status: :ok, location: @siswa }
      else
        format.html { render :edit }
        format.json { render json: @siswa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /siswas/1
  # DELETE /siswas/1.json
  def destroy
    @siswa.destroy
    respond_to do |format|
      format.html { redirect_to siswas_url, notice: 'Siswa was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_siswa
      @siswa = Siswa.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def siswa_params
      params.require(:siswa).permit(:nama, :kelas, :skor_uts, :skor_uas, :rata_rata)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/siswas_helper.rb
module SiswasHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/siswas/_form.html.erb
<%= form_for(siswa) do |f| %>
  <% if siswa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(siswa.errors.count, "error") %> prohibited this siswa from being saved:</h2>

      <ul>
      <% siswa.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nama %>
    <%= f.text_field :nama %>
  </div>

  <div class="field">
    <%= f.label :kelas %>
    <%= f.text_field :kelas %>
  </div>

  <div class="field">
    <%= f.label :skor_uts %>
    <%= f.number_field :skor_uts %>
  </div>

  <div class="field">
    <%= f.label :skor_uas %>
    <%= f.number_field :skor_uas %>
  </div>

  <div class="field">
    <%= f.label :rata_rata %>
    <%= f.text_field :rata_rata %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<script>
  $(document).ready(function(){
    $("#siswa_skor_uas").change(function(){
      var_skor_uts = parseInt($("#siswa_skor_uts").val());
      var_skor_uas = parseInt($("#siswa_skor_uas").val());
      $("#siswa_rata_rata").val((var_skor_uts * 0.3) +( var_skor_uas * 0.7));
    });
  });
</script>

app/views/siswas/edit.html.erb
<h1>Editing Siswa</h1>

<%= render 'form', siswa: @siswa %>

<%= link_to 'Show', @siswa %> |
<%= link_to 'Back', siswas_path %>

app/views/siswas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Siswas</h1>

<table>
  <thead>
    <tr>
      <th>Nama</th>
      <th>Kelas</th>
      <th>Skor uts</th>
      <th>Skor uas</th>
      <th>Rata rata</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @siswas.each do |siswa| %>
      <tr>
        <td><%= siswa.nama %></td>
        <td><%= siswa.kelas %></td>
        <td><%= siswa.skor_uts %></td>
        <td><%= siswa.skor_uas %></td>
        <td><%= siswa.rata_rata %></td>
        <td><%= link_to 'Show', siswa %></td>
        <td><%= link_to 'Edit', edit_siswa_path(siswa) %></td>
        <td><%= link_to 'Destroy', siswa, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Siswa', new_siswa_path %>

app/views/siswas/new.html.erb
<h1>New Siswa</h1>

<%= render 'form', siswa: @siswa %>

<%= link_to 'Back', siswas_path %>

app/views/siswas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nama:</strong>
  <%= @siswa.nama %>
</p>

<p>
  <strong>Kelas:</strong>
  <%= @siswa.kelas %>
</p>

<p>
  <strong>Skor uts:</strong>
  <%= @siswa.skor_uts %>
</p>

<p>
  <strong>Skor uas:</strong>
  <%= @siswa.skor_uas %>
</p>

<p>
  <strong>Rata rata:</strong>
  <%= @siswa.rata_rata %>
</p>

<%= link_to 'Edit', edit_siswa_path(@siswa) %> |
<%= link_to 'Back', siswas_path %>

<div id="grafik_siswa" style="height:400px;width:50%;"></div>
<br><br>
<div><canvas id="grafik_siswa2" style="height:500px;width:100%;"></canvas></div>

<script>
  $(function () {
    var graph = {
      title: {
        text: "Grafik Nilai <%= @siswa.nama %>"
      },
      animationEnabled: true,
      data: [
      {
        type: "splineArea",
        dataPoints: [
          { y: parseInt("<%= @siswa.skor_uts %>"), label: "UAS"},
          { y: parseInt("<%= @siswa.skor_uas %>"), label: "UTS"},
          { y: parseInt("<%= @siswa.rata_rata %>"), label: "Rata-rata"}
        ]
      }
      ]
    };
    $("#grafik_siswa").CanvasJSChart(graph);
  });

  $(function() {
    var ctx = document.getElementById("grafik_siswa2");
    var myChart = new Chart(ctx, {
      type: 'bar',
      data: {
        labels: ["UAS", "UTS", "Rata-rata"],
        datasets: [{
          label: '# Nilai ',
          data: [parseInt("<%= @siswa.skor_uts %>"), parseInt("<%= @siswa.skor_uas %>"), parseInt("<%= @siswa.rata_rata %>")],
          backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)'
            ],
          borderColor: [
                'rgba(255,99,132,1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)'
            ],
          borderWidth: 1
        }]
      },
      options: {
        scales: {
          yAxes: [{
            ticks: {
              beginAtZero:true
            }
          }]
        },
        title: {
          display: true,
          text: 'Grafik Nilai <%= @siswa.nama %>',
          fontSize: 24
        },
        tooltips: {
          enabled: true,
          mode: 'single',
          callbacks: {
            label: function(tooltipItems, data) {
              var ylabel = tooltipItems.yLabel;
              return " # Nilai : " + ylabel;
            }
          }
        }
      }
    });
  });
</script>